#####
avatar: 
favicon: 
preload: true #字体预加载
excerpt_length: 300 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳  
tag_page_count: true #Tag页是否计数
mourn_mode: false #哀悼模式

# 主题颜色
theme_color:
  primary: teal 
  accent: blue

# 搜索
search:
  local: true
  path: /search.xml
  placeholder: 请输入关键字

# Google Adsense广告代码
google_adsense:
  enabled: true #开启广告
  auto_ad: true #自动广告
  page_ad: false  #单页启用广告
  pub_id: 
  footer_slot: 
  sidebar_slot: 
  banner_slot: 

#####文章#####
# 文末结束语
passage_end_tag:
  enabled: true
  text: --- 本文结束 <i class="iconfont icon-heartbeat" style="font-size:24px;"></i> The End ---

# 数学公式渲染
math:
  enabled: true
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mhchem: true  #化学式扩展
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# mermaid图
mermaid:
  enable: true 
  version: "8.4.8" 
  startOnload: true  #default true
  theme: 'default'    #default, forest, dark, neutral.
##########

#####侧边栏#####
# 菜单
menu:
  home: / || icon-home
  tags: /tags/ || icon-bookmark
  categories: /categories/ || icon-folder
  archives: /archives/ || icon-archive 
  工具箱: /tools/ || icon-tools
  about: /about/ || icon-user
  #gallery: /categories/图集/ || icon-gallery

# 社交链接
social:
  E-Mail: mailto:xxx@xxx.com || icon-mail
  GitHub: https://your.url || icon-github
  Steam: https://your.url || icon-steam
  Weibo: https://your.url || icon-weibo
  # 此外还预置了以下社交图标，可直接仿照格式进行引用，如需其他图标请自行添加图标库或与我联系
  # icon-twitter、icon-facebook、icon-vk、icon-stack-overflow、icon-youtube、icon-Instagram、icon-skype
  # icon-qq、icon-wechat、icon-alipay、icon-paypal、icon-telegram、icon-twitch、icon-discord

#友情链接
links:
  Meadow说明文档: https://garybear.cn/hexo-theme-meadow/
##########

#####页脚#####
# 页脚
footer:
  since: 2015
  powered: true
  theme: true
  beian:
    enable: true
    icp: 
  icon:
    enabled: true
    name: icon-heart
    color: "#d9333f"

# 不蒜子计数
busuanzi:
  site: true
  page: true
  busuanzi_js: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
##########

#####第三方服务#####
# 评论
comment:
  use: 
    - gitalk
    - livere
  ## Gitalk
  gitalk_client_id: 
  gitalk_client_secret: 
  gitalk_repo: 
  gitalk_owner: 
  gitalk_sid_type:
  gitalk_distractionFreeMode: true
  ## Disqus
  disqus_shortname:
  ## Livere
  livere_data_uid: 
  ## Valine
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  ## 畅言
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

# 分析
analytics:
  google_analytics:
    tracking_id: 
    localhost_ignored: true
  baidu_site_id:
  cnzz_site_id:
  tencent_site_id:
##########